<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_602cf8ac82a5f',
	'title' => 'Market Report Options',
	'fields' => array(
		array(
			'key' => 'field_602cf8bcabc1d',
			'label' => 'Market Report JSON URL',
			'name' => 'ifx_market_report_json_url',
			'type' => 'url',
			'instructions' => 'Include the IFX Market Report JSON URL here.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_602cf8fcabc1e',
			'label' => 'Market Report Title',
			'name' => 'ifx_market_report_title',
			'type' => 'text',
			'instructions' => 'This text field serves two purposes. First it is prepended to the formatted current JSON date to create a title to check. This is then checked against all posts. If no posts are found with this title, a new post is created, using this field plus the formatted date in the JSON.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_602d02a788873',
			'label' => 'Market Report Post Category',
			'name' => 'ifx_market_report_post_category',
			'type' => 'taxonomy',
			'instructions' => 'Select the post category that Market Reports should be linked to.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category',
			'field_type' => 'select',
			'allow_null' => 0,
			'add_term' => 1,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'acfe_bidirectional' => array(
				'acfe_bidirectional_enabled' => '0',
			),
			'multiple' => 0,
		),
		array(
			'key' => 'field_602d04342f82d',
			'label' => 'Market Report Post Author',
			'name' => 'ifx_market_report_post_author',
			'type' => 'user',
			'instructions' => 'Select the user that Market Reports should be assigned to.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'role' => '',
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'id',
			'acfe_bidirectional' => array(
				'acfe_bidirectional_enabled' => '0',
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-market-report-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => '',
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
));

endif;
?>